// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkGu8cIcOeW9GHrkv_IpO_8dYJ2s9JSXQ',
    appId: '1:263373154141:web:0aa2a0a6ef44227598eab4',
    messagingSenderId: '263373154141',
    projectId: 'mynotes-efc0f',
    authDomain: 'mynotes-efc0f.firebaseapp.com',
    storageBucket: 'mynotes-efc0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbupdiS5pY60gi5hk_mEOJCArdCASoyB4',
    appId: '1:263373154141:android:b08132c7c65e4f1c98eab4',
    messagingSenderId: '263373154141',
    projectId: 'mynotes-efc0f',
    storageBucket: 'mynotes-efc0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdDrsEaBldRLoKMY7GPIqv8w3vVXe91Hg',
    appId: '1:263373154141:ios:92bbdba32f65e28398eab4',
    messagingSenderId: '263373154141',
    projectId: 'mynotes-efc0f',
    storageBucket: 'mynotes-efc0f.appspot.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdDrsEaBldRLoKMY7GPIqv8w3vVXe91Hg',
    appId: '1:263373154141:ios:a8c11bf76870c33e98eab4',
    messagingSenderId: '263373154141',
    projectId: 'mynotes-efc0f',
    storageBucket: 'mynotes-efc0f.appspot.com',
    iosBundleId: 'com.example.myNotes.RunnerTests',
  );
}
